modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "nucleoplasm_api"
version = "${version}"
displayName = "Nucleoplasm Api Mod"
authors = "${org_name}"
description = "${mod_description}"
#logoFile = ""

[[dependencies.nucleoplasm_api]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nucleoplasm_api]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nucleoplasm_api]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"