package org.overrun.nucleoplasm_nuclide.decay;

import net.minecraft.world.item.ItemStack;

import java.util.HashMap;
import java.util.Map;

import static org.overrun.nucleoplasm_nuclide.registry.ModItems.*;
import static org.overrun.nucleoplasm_nuclide.registry.ModItems.H;

public class DecayUtils {
    public static final Map<Integer, Integer> mass_number = new HashMap<>();
    static {
        mass_number.put(1, 7);
        mass_number.put(2, 10);
        mass_number.put(3, 12);
        mass_number.put(4, 16);
        mass_number.put(5, 21);
        mass_number.put(6, 22);
        mass_number.put(7, 24);
        mass_number.put(8, 26);
        mass_number.put(9, 31);
        mass_number.put(10, 34);
        mass_number.put(11, 37);
        mass_number.put(12, 40);
        mass_number.put(13, 43);
        mass_number.put(14, 44);
        mass_number.put(15, 46);
        mass_number.put(16, 48);
        mass_number.put(17, 51);
        mass_number.put(18, 53);
        mass_number.put(19, 56);
        mass_number.put(20, 58);
        mass_number.put(21, 61);
        mass_number.put(22, 64);
        mass_number.put(23, 67);
        mass_number.put(24, 70);
        mass_number.put(25, 73);
        mass_number.put(26, 75);
        mass_number.put(27, 77);
        mass_number.put(28, 82);
        mass_number.put(29, 82);
        mass_number.put(30, 85);
        mass_number.put(31, 87);
        mass_number.put(32, 90);
        mass_number.put(33, 92);
        mass_number.put(34, 95);
        mass_number.put(35, 98);
        mass_number.put(36, 101);
        mass_number.put(37, 103);
        mass_number.put(38, 107);
        mass_number.put(39, 109);
        mass_number.put(40, 112);
        mass_number.put(41, 115);
        mass_number.put(42, 118);
        mass_number.put(43, 121);
        mass_number.put(44, 124);
        mass_number.put(45, 127);
        mass_number.put(46, 129);
        mass_number.put(47, 132);
        mass_number.put(48, 134);
        mass_number.put(49, 137);
        mass_number.put(50, 139);
        mass_number.put(51, 141);
        mass_number.put(52, 144);
        mass_number.put(53, 145);
        mass_number.put(54, 148);
        mass_number.put(55, 152);
        mass_number.put(56, 154);
        mass_number.put(57, 156);
        mass_number.put(58, 158);
        mass_number.put(59, 160);
        mass_number.put(60, 162);
        mass_number.put(61, 163);
        mass_number.put(62, 166);
        mass_number.put(63, 168);
        mass_number.put(64, 170);
        mass_number.put(65, 172);
        mass_number.put(66, 174);
        mass_number.put(67, 177);
        mass_number.put(68, 178);
        mass_number.put(69, 181);
        mass_number.put(70, 185);
        mass_number.put(71, 188);
        mass_number.put(72, 190);
        mass_number.put(73, 194);
        mass_number.put(74, 197);
        mass_number.put(75, 199);
        mass_number.put(76, 203);
        mass_number.put(77, 205);
        mass_number.put(78, 208);
        mass_number.put(79, 210);
        mass_number.put(80, 216);
        mass_number.put(81, 217);
        mass_number.put(82, 220);
        mass_number.put(83, 224);
        mass_number.put(84, 227);
        mass_number.put(85, 229);
        mass_number.put(86, 229);
        mass_number.put(87, 233);
        mass_number.put(88, 234);
        mass_number.put(89, 236);
        mass_number.put(90, 238);
        mass_number.put(91, 239);
        mass_number.put(92, 243);
        mass_number.put(93, 244);
        mass_number.put(94, 247);
        mass_number.put(95, 248);
        mass_number.put(96, 252);
        mass_number.put(97, 253);
        mass_number.put(98, 256);
        mass_number.put(99, 257);
        mass_number.put(100, 259);
        mass_number.put(101, 260);
        mass_number.put(102, 262);
        mass_number.put(103, 266);
        mass_number.put(104, 267);
        mass_number.put(105, 270);
        mass_number.put(106, 271);
        mass_number.put(107, 278);
        mass_number.put(108, 278);
        mass_number.put(109, 282);
        mass_number.put(110, 282);
        mass_number.put(111, 286);
        mass_number.put(112, 286);
        mass_number.put(113, 290);
        mass_number.put(114, 290);
        mass_number.put(115, 290);
        mass_number.put(116, 294);
        mass_number.put(117, 294);
        mass_number.put(118, 294);
    }
    public static ItemStack getStack(int proton) {
        return new ItemStack(
                switch (proton) {
                    case 1  -> H.get();
                    case 2  -> He.get();
                    case 3  -> Li.get();
                    case 4  -> Be.get();
                    case 5  -> B.get();
                    case 6  -> C.get();
                    case 7  -> N.get();
                    case 8  -> O.get();
                    case 9  -> F.get();
                    case 10 -> Ne.get();
                    case 12 -> Na.get();
                    case 13 -> Mg.get();
                    case 14 -> Al.get();
                    case 15 -> Si.get();
                    case 16 -> P.get();
                    case 17 -> S.get();
                    case 18 -> Cl.get();
                    case 19 -> Ar.get();
                    case 20 -> K.get();
                    case 21 -> Ca.get();
                    case 22 -> Sc.get();
                    case 23 -> V.get();
                    case 24 -> Cr.get();
                    case 25 -> Mn.get();
                    case 26 -> Fe.get();
                    case 27 -> Co.get();
                    case 28 -> Ni.get();
                    case 29 -> Cu.get();
                    case 30 -> Zn.get();
                    case 31 -> Ga.get();
                    case 32 -> Ge.get();
                    case 33 -> As.get();
                    case 34 -> Se.get();
                    case 35 -> Br.get();
                    case 36 -> Kr.get();
                    case 37 -> Rb.get();
                    case 38 -> Sr.get();
                    case 39 -> Y.get();
                    case 40 -> Zr.get();
                    case 41 -> Nb.get();
                    case 42 -> Mo.get();
                    case 43 -> Tc.get();
                    case 44 -> Ru.get();
                    case 45 -> Rh.get();
                    case 46 -> Pd.get();
                    case 47 -> Ag.get();
                    case 48 -> Cd.get();
                    case 49 -> In.get();
                    case 50 -> Sn.get();
                    case 51 -> Sb.get();
                    case 52 -> Te.get();
                    case 53 -> I.get();
                    case 54 -> Xe.get();
                    case 55 -> Cs.get();
                    case 56 -> Ba.get();
                    case 57 -> La.get();
                    case 58 -> Ce.get();
                    case 59 -> Pr.get();
                    case 60 -> Nd.get();
                    case 61 -> Pm.get();
                    case 62 -> Sm.get();
                    case 63 -> Eu.get();
                    case 64 -> Gd.get();
                    case 65 -> Tb.get();
                    case 66 -> Dy.get();
                    case 67 -> Ho.get();
                    case 68 -> Er.get();
                    case 69 -> Tm.get();
                    case 70 -> Yb.get();
                    case 71 -> Lu.get();
                    case 72 -> Hf.get();
                    case 73 -> Ta.get();
                    case 74 -> W.get();
                    case 75 -> Re.get();
                    case 76 -> Os.get();
                    case 77 -> Ir.get();
                    case 78 -> Pt.get();
                    case 79 -> Au.get();
                    case 80 -> Hg.get();
                    case 81 -> Tl.get();
                    case 82 -> Pb.get();
                    case 83 -> Bi.get();
                    case 84 -> Po.get();
                    case 85 -> At.get();
                    case 86 -> Rn.get();
                    case 87 -> Fr.get();
                    case 88 -> Ra.get();
                    case 89 -> Ac.get();
                    case 90 -> Th.get();
                    case 91 -> Pa.get();
                    case 92 -> U.get();
                    case 93 -> Np.get();
                    case 94 -> Pu.get();
                    case 95 -> Am.get();
                    case 96 -> Cm.get();
                    case 97 -> Bk.get();
                    case 98 -> Cf.get();
                    case 99 -> Es.get();
                    case 100-> Fm.get();
                    case 101-> Md.get();
                    case 102-> No.get();
                    case 103-> Lr.get();
                    case 104-> Rf.get();
                    case 105-> Db.get();
                    case 106-> Sg.get();
                    case 107-> Bh.get();
                    case 108-> Hs.get();
                    case 109-> Mt.get();
                    case 110-> Ds.get();
                    case 111-> Rg.get();
                    case 112-> Cn.get();
                    case 113-> Nh.get();
                    case 114-> Fl.get();
                    case 115-> Mc.get();
                    case 116-> Lv.get();
                    case 117-> Ts.get();
                    case 118-> Og.get();
                    default -> elementItem.get();
                }
        );
    }
}
